config/routes.rb
Mahesh::Application.routes.draw do
  get "mahesh/home"

  get "mahesh/nenokkadine"

  get "mahesh/gallery"

  get "mahesh/videos"

  get "mahesh/login"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mahesh_controller.rb
class MaheshController < ApplicationController
  def home
  end

  def nenokkadine
  end

  def gallery
  end

  def videos
  end

  def login
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mahesh_helper.rb
module MaheshHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mahesh</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
   <div class="container1">
      <!--start title-->
      <h1 class="fontface" id="title"><span class="orange">M</span><span class="pink">a</span><span class="purple">h</span><span class="blue ">e</span><span class="green ">sh</span></h1>
      <!--end title-->
      <!--start menu-->
      <nav>
      <ul>
      <li><%= link_to "Home",mahesh_home_path %></li>
      <li><%= link_to "Nenokkadine",mahesh_nenokkadine_path %></li>
      <li><%= link_to "Gallery",mahesh_gallery_path %></li>
      <li><%= link_to "Videos",mahesh_videos_path %></li>
      <li><%= link_to "Login",mahesh_login_path %></li>
      </ul>
      </nav>
   </div>
   <div class="bottom"> </div>
   <!--end menu-->
   <!--end header-->
</header>

<%= yield %>
<div id="container">
   <!--start intro-->
   <section id="intro">
     <div class="quote">
      <section class="welcome">
      <h2 class="fontface"> <span class="pink medium">100% Wild </span><span class="green small rotate">and </span>Crazy<span class="orange medium"> Grunge</span></h2> 
     </div>
   </section>
   <!--end intro-->
   
      

   <section id="main">
      <div class="portfolio">
      <h2 class="fontface"> <span class="orange ">Gal</span><span class="pink">lery</span></h2> 
       </div>
      <br><br>
      <ul class="gallery">
      <li><%= image_tag "11.jpg" %></li>
      <li><%= image_tag "9.jpg" %></li>
      <li><%= image_tag "4.jpg" %></li>
      <li><%= image_tag "7.jpg" %></li>
      <li><%= image_tag "5.jpg" %></li>
      <li><%= image_tag "6.jpg" %></li>
      <li><%= image_tag "3.jpg" %></li>
      <li><%= image_tag "1.jpg" %></li>
      </ul>
      </section>
   </div>

 <footer>

   <div class="container1">
     <p> Copyright © 2013 | Developed by Harikrishna</p> 
   </div>
   
   </footer>
</body>
</html>

app/views/mahesh/gallery.html.erb
<h1>Mahesh#gallery</h1>
<p>Find me in app/views/mahesh/gallery.html.erb</p>

app/views/mahesh/login.html.erb
<h1>Mahesh#login</h1>
<p>Find me in app/views/mahesh/login.html.erb</p>

app/views/mahesh/nenokkadine.html.erb
<h1>Mahesh#nenokkadine</h1>
<p>Find me in app/views/mahesh/nenokkadine.html.erb</p>

app/views/mahesh/videos.html.erb
<h1>Mahesh#videos</h1>
<p>Find me in app/views/mahesh/videos.html.erb</p>